"""in artwordreview changed date_completed from date to str

Revision ID: 74ae7e07f830
Revises: 7685d84a2ff3
Create Date: 2026-08-26 14:34:47.791497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74ae7e07f830'
down_revision = '7685d84a2ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_reviews', schema=None) as batch_op:
        batch_op.alter_column('date_completed',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork_reviews', schema=None) as batch_op:
        batch_op.alter_column('date_completed',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
