"""ensure db is up to date

Revision ID: 7685d84a2ff3
Revises: 842c1daa9cba
Create Date: 2026-08-26 13:44:53.345201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7685d84a2ff3'
down_revision = '842c1daa9cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
