"""initial migration

Revision ID: 842c1daa9cba
Revises: 
Create Date: 2026-08-17 12:14:48.930657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842c1daa9cba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artist_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_img', sa.String(), nullable=True),
    sa.Column('reason_for_liking', sa.String(), nullable=True),
    sa.Column('location_viewed', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artist_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artwork_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('date_completed', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('item_img', sa.String(), nullable=True),
    sa.Column('reason_for_liking', sa.String(), nullable=True),
    sa.Column('location_viewed', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_artwork_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('collection_img', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collections_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_collection_join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_review_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_review_id'], ['artist_reviews.id'], name=op.f('fk_artist_collection_join_artist_review_id_artist_reviews')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_artist_collection_join_collection_id_collections')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'artist_review_id', name='uq_collection_artist')
    )
    op.create_table('artwork_collection_join',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artwork_review_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artwork_review_id'], ['artwork_reviews.id'], name=op.f('fk_artwork_collection_join_artwork_review_id_artwork_reviews')),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_artwork_collection_join_collection_id_collections')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'artwork_review_id', name='uq_collection_artwork')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artwork_collection_join')
    op.drop_table('artist_collection_join')
    op.drop_table('collections')
    op.drop_table('artwork_reviews')
    op.drop_table('artist_reviews')
    op.drop_table('users')
    # ### end Alembic commands ###
